export { default as RegisterPage} from './auth/RegisterPage'
export { default as LoginPage} from './auth/LoginPage'
export { default as ForgotPasswordPage} from './auth/ForgotPasswordPage'
export { default as ReAssignPasswordPage } from './auth/ReAssignPasswordPage'
export { default as SelectCompany } from './auth/SelectCompany'